//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XjzzDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LoginUserName { get; set; }
        public string FamilyName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string EnglishFamilyName { get; set; }
        public string EnglishFirstName { get; set; }
        public string EnglishFullName { get; set; }
        public string Sex { get; set; }
        public string ProfTitle { get; set; }
        public string Dept { get; set; }
        public string Lab { get; set; }
        public string Group { get; set; }
        public string Types { get; set; }
        public string Education { get; set; }
        public string Position { get; set; }
        public int State { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string WeiXin { get; set; }
        public string OfficePhone { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePositon { get; set; }
        public string EmergencyPhone { get; set; }
        public string IdNumbers { get; set; }
        public string EmergencyPerson { get; set; }
        public string Nationality { get; set; }
        public string Nation { get; set; }
        public string NativePlace { get; set; }
        public string OtherNames { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime DateWhenIn { get; set; }
        public string PicPath { get; set; }
        public string EduHistory { get; set; }
        public string WorkHistory { get; set; }
    }
}
