//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XjzzDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LoginUserName { get; set; }
        public string StudentId { get; set; }
        public string FamilyName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string EnglishFamilyName { get; set; }
        public string EnglishFirstName { get; set; }
        public string EnglishFullName { get; set; }
        public string Sex { get; set; }
        public string Tutor { get; set; }
        public string AsistTutor { get; set; }
        public string AsistTutorEx { get; set; }
        public string Major_ { get; set; }
        public string MobilePhone { get; set; }
    }
}
