<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EmployeeDetails.aspx.cs" Inherits="XjzzDatabase.DataTable.EmployeeDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="body-content">  
        <div class="form group">
            <asp:Button ID="Button_EnterSelect" runat="server" CssClass="btn btn-default"   Text="显示" />
            <asp:Button ID="Button_EnterEdit" runat="server" CssClass="btn btn-default" Text="编辑" />
            <asp:Button ID="Button_EnterDelete" runat="server" CssClass="btn btn-default"  Text="删除" />
        </div>

        <asp:FormView ID="FormViewEmployee" runat="server"  Width="760px" ItemType="XjzzDatabase.Models.Employee" SelectMethod ="FormViewEmployee_GetItem" 
            UpdateMethod ="FormViewEmployee_UpdateItem" DeleteMethod ="FormViewEmployee_DeleteItem" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
            <EditItemTemplate>
                Id:
                <asp:Label ID="IdLabel1" runat="server" Text='<%# Eval("Id") %>' />
                <br />
                LoginUserName:
                <asp:TextBox ID="LoginUserNameTextBox" runat="server" Text='<%# Bind("LoginUserName") %>' />
                <br />
                FamilyName:
                <asp:TextBox ID="FamilyNameTextBox" runat="server" Text='<%# Bind("FamilyName") %>' />
                <br />
                FirstName:
                <asp:TextBox ID="FirstNameTextBox" runat="server" Text='<%# Bind("FirstName") %>' />
                <br />
                EnglishFamilyName:
                <asp:TextBox ID="EnglishFamilyNameTextBox" runat="server" Text='<%# Bind("EnglishFamilyName") %>' />
                <br />
                EnglishFirstName:
                <asp:TextBox ID="EnglishFirstNameTextBox" runat="server" Text='<%# Bind("EnglishFirstName") %>' />
                <br />
                Sex:
                <asp:TextBox ID="SexTextBox" runat="server" Text='<%# Bind("Sex") %>' />
                <br />
                ProfTitle:
                <asp:TextBox ID="ProfTitleTextBox" runat="server" Text='<%# Bind("ProfTitle") %>' />
                <br />
                Dept:
                <asp:TextBox ID="DeptTextBox" runat="server" Text='<%# Bind("Dept") %>' />
                <br />
                Lab:
                <asp:TextBox ID="LabTextBox" runat="server" Text='<%# Bind("Lab") %>' />
                <br />
                Types:
                <asp:TextBox ID="TypesTextBox" runat="server" Text='<%# Bind("Types") %>' />
                <br />
                Education:
                <asp:TextBox ID="EducationTextBox" runat="server" Text='<%# Bind("Education") %>' />
                <br />
                Position:
                <asp:TextBox ID="PositionTextBox" runat="server" Text='<%# Bind("Position") %>' />
                <br />
                State:
                <asp:TextBox ID="StateTextBox" runat="server" Text='<%# Bind("State") %>' />
                <br />
                Email:
                <asp:TextBox ID="EmailTextBox" runat="server" Text='<%# Bind("Email") %>' />
                <br />
                OfficePhone:
                <asp:TextBox ID="OfficePhoneTextBox" runat="server" Text='<%# Bind("OfficePhone") %>' />
                <br />
                MobilePhone:
                <asp:TextBox ID="MobilePhoneTextBox" runat="server" Text='<%# Bind("MobilePhone") %>' />
                <br />
                OfficePositon:
                <asp:TextBox ID="OfficePositonTextBox" runat="server" Text='<%# Bind("OfficePositon") %>' />
                <br />
                EmergencyPhone:
                <asp:TextBox ID="EmergencyPhoneTextBox" runat="server" Text='<%# Bind("EmergencyPhone") %>' />
                <br />
                IdNumbers:
                <asp:TextBox ID="IdNumbersTextBox" runat="server" Text='<%# Bind("IdNumbers") %>' />
                <br />
                EmergencyPerson:
                <asp:TextBox ID="EmergencyPersonTextBox" runat="server" Text='<%# Bind("EmergencyPerson") %>' />
                <br />
                Nationality:
                <asp:TextBox ID="NationalityTextBox" runat="server" Text='<%# Bind("Nationality") %>' />
                <br />
                Nation:
                <asp:TextBox ID="NationTextBox" runat="server" Text='<%# Bind("Nation") %>' />
                <br />
                NativePlace:
                <asp:TextBox ID="NativePlaceTextBox" runat="server" Text='<%# Bind("NativePlace") %>' />
                <br />
                OtherNames:
                <asp:TextBox ID="OtherNamesTextBox" runat="server" Text='<%# Bind("OtherNames") %>' />
                <br />
                Birthday:
                <asp:TextBox ID="BirthdayTextBox" runat="server" Text='<%# Bind("Birthday") %>' />
                <br />
                DateWhenIn:
                <asp:TextBox ID="DateWhenInTextBox" runat="server" Text='<%# Bind("DateWhenIn") %>' />
                <br />
                <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="更新" />
                &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="取消" />
            </EditItemTemplate>
            <ItemTemplate>
                Id:
                <asp:Label ID="IdLabel" runat="server" Text='<%# Eval("Id") %>' />
                <br />
                LoginUserName:
                <asp:Label ID="LoginUserNameLabel" runat="server" Text='<%# Bind("LoginUserName") %>' />
                <br />
                FamilyName:
                <asp:Label ID="FamilyNameLabel" runat="server" Text='<%# Bind("FamilyName") %>' />
                <br />
                FirstName:
                <asp:Label ID="FirstNameLabel" runat="server" Text='<%# Bind("FirstName") %>' />
                <br />
                EnglishFamilyName:
                <asp:Label ID="EnglishFamilyNameLabel" runat="server" Text='<%# Bind("EnglishFamilyName") %>' />
                <br />
                EnglishFirstName:
                <asp:Label ID="EnglishFirstNameLabel" runat="server" Text='<%# Bind("EnglishFirstName") %>' />
                <br />
                Sex:
                <asp:Label ID="SexLabel" runat="server" Text='<%# Bind("Sex") %>' />
                <br />
                ProfTitle:
                <asp:Label ID="ProfTitleLabel" runat="server" Text='<%# Bind("ProfTitle") %>' />
                <br />
                Dept:
                <asp:Label ID="DeptLabel" runat="server" Text='<%# Bind("Dept") %>' />
                <br />
                Lab:
                <asp:Label ID="LabLabel" runat="server" Text='<%# Bind("Lab") %>' />
                <br />
                Types:
                <asp:Label ID="TypesLabel" runat="server" Text='<%# Bind("Types") %>' />
                <br />
                Education:
                <asp:Label ID="EducationLabel" runat="server" Text='<%# Bind("Education") %>' />
                <br />
                Position:
                <asp:Label ID="PositionLabel" runat="server" Text='<%# Bind("Position") %>' />
                <br />
                State:
                <asp:Label ID="StateLabel" runat="server" Text='<%# Bind("State") %>' />
                <br />
                Email:
                <asp:Label ID="EmailLabel" runat="server" Text='<%# Bind("Email") %>' />
                <br />
                OfficePhone:
                <asp:Label ID="OfficePhoneLabel" runat="server" Text='<%# Bind("OfficePhone") %>' />
                <br />
                MobilePhone:
                <asp:Label ID="MobilePhoneLabel" runat="server" Text='<%# Bind("MobilePhone") %>' />
                <br />
                OfficePositon:
                <asp:Label ID="OfficePositonLabel" runat="server" Text='<%# Bind("OfficePositon") %>' />
                <br />
                EmergencyPhone:
                <asp:Label ID="EmergencyPhoneLabel" runat="server" Text='<%# Bind("EmergencyPhone") %>' />
                <br />
                IdNumbers:
                <asp:Label ID="IdNumbersLabel" runat="server" Text='<%# Bind("IdNumbers") %>' />
                <br />
                EmergencyPerson:
                <asp:Label ID="EmergencyPersonLabel" runat="server" Text='<%# Bind("EmergencyPerson") %>' />
                <br />
                Nationality:
                <asp:Label ID="NationalityLabel" runat="server" Text='<%# Bind("Nationality") %>' />
                <br />
                Nation:
                <asp:Label ID="NationLabel" runat="server" Text='<%# Bind("Nation") %>' />
                <br />
                NativePlace:
                <asp:Label ID="NativePlaceLabel" runat="server" Text='<%# Bind("NativePlace") %>' />
                <br />
                OtherNames:
                <asp:Label ID="OtherNamesLabel" runat="server" Text='<%# Bind("OtherNames") %>' />
                <br />
                Birthday:
                <asp:Label ID="BirthdayLabel" runat="server" Text='<%# Bind("Birthday") %>' />
                <br />
                DateWhenIn:
                <asp:Label ID="DateWhenInLabel" runat="server" Text='<%# Bind("DateWhenIn") %>' />
                <br />
            </ItemTemplate>
        </asp:FormView>
    </div>
</asp:Content>
