CREATE TABLE [dbo].[Employee] (
    [Id]              INT            NOT NULL,
    [LoginUserName]   NVARCHAR (256) NOT NULL,
    [FamilyName]      NVARCHAR (30)  NOT NULL,
	[FirstName]		  NVARCHAR (30)  NOT NULL,
	[EnglishFamilyName]	NVARCHAR (30)  NULL,
	[EnglishFirstName]  NVARCHAR (30)  NULL,
    [Sex]             NVARCHAR (1)   DEFAULT (N'男') NOT NULL,
    [ProfTitle]       NVARCHAR (30)  NULL,
    [Dept]            NVARCHAR (50)  NULL,
    [Lab]             NVARCHAR (50)  NULL,
    [Types]           NVARCHAR (10)  NULL,
    [Education]       NVARCHAR (10)  NULL,
    [Position]        NVARCHAR (30)  NULL,
    [State]           NVARCHAR (10)  NULL,
    [Email]           NVARCHAR (50)  NULL,
    [OfficePhone]     NVARCHAR (20)  NULL,
    [MobilePhone]     NVARCHAR (50)  NULL,
    [OfficePositon]   NVARCHAR (50)  NULL,
    [EmergencyPhone]  NVARCHAR (20)  NULL,
    [IdNumbers]       NVARCHAR (30)  NULL,
    [EmergencyPerson] NVARCHAR (30)  NULL,
    [Nationality]     NVARCHAR (30)  NULL,
    [Nation]          NVARCHAR (20)  NULL,
    [NativePlace]     NVARCHAR (30)  NULL,
    [OtherNames]      NVARCHAR (50)  NULL,
    [Birthday]        DATETIME2 (7)  DEFAULT ('1900-1-1') NOT NULL,
    [DateWhenIn]      DATETIME2 (7)  DEFAULT ('1900-1-1') NOT NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [CK_Employee_Sex] CHECK ([Sex]=N'男' OR [Sex]=N'女')
);

